title: Ferluht
description: finally I made a blog
author: "2022"
image: "/assets/imgs/avatar.jpg"

theme: minima

# base_url: /

twitter_username: ferluht
github_username: ferluht
instagram_username: neurussia

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: ferluht
    github: ferluht
    instagram: neurussia

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
